require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Fragment caching is always on in development so you can test cache
  # behaviour without running `bin/rails dev:cache` each time.
  config.action_controller.perform_caching = true
  config.action_controller.enable_fragment_cache_logging = true
  config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }

  # Memory store is fine for a single-process dev server.
  # Switch to :redis_cache_store or :solid_cache_store for multi-process.
  config.cache_store = :memory_store

  # Storage backend priority:
  #   1. MinIO (local S3-compatible) when MINIO_ACCESS_KEY is set
  #   2. Amazon S3 when AWS_ACCESS_KEY_ID is set
  #   3. Local disk (default, no config needed)
  config.active_storage.service =
    if ENV["MINIO_ACCESS_KEY"].present?
      :minio
    elsif ENV["AWS_ACCESS_KEY_ID"].present?
      :amazon
    else
      :local
    end

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Mail delivery in development.
  #
  # If SMTP_USERNAME and SMTP_PASSWORD are set in the environment, emails are
  # sent for real via SMTP (Gmail by default; override with SMTP_ADDRESS /
  # SMTP_PORT / SMTP_DOMAIN). Otherwise emails are written to
  # tmp/mails/<recipient> so you can preview them without configuring SMTP.
  if ENV["SMTP_USERNAME"].present? && ENV["SMTP_PASSWORD"].present?
    config.action_mailer.delivery_method = :smtp
    config.action_mailer.smtp_settings = {
      address:              ENV.fetch("SMTP_ADDRESS", "smtp.gmail.com"),
      port:                 ENV.fetch("SMTP_PORT", 587).to_i,
      domain:               ENV.fetch("SMTP_DOMAIN", "gmail.com"),
      user_name:            ENV["SMTP_USERNAME"],
      password:             ENV["SMTP_PASSWORD"],
      authentication:       :plain,
      enable_starttls_auto: true
    }
    # Surface SMTP errors loudly while you're setting it up.
    config.action_mailer.raise_delivery_errors = true

    # Use the SMTP username as the From: address so the mail is actually
    # accepted by Gmail / most providers (they reject spoofed From headers).
    ActionMailer::Base.default from: ENV.fetch("MAIL_FROM", ENV["SMTP_USERNAME"])
  else
    config.action_mailer.delivery_method = :file
    config.action_mailer.file_settings   = { location: Rails.root.join("tmp/mails") }
  end

  # Background jobs are processed by Sidekiq (requires Redis + sidekiq process).
  config.active_job.queue_adapter = :sidekiq

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
